export class DataboxDB {
  public databox_items = [
    {
      '_id': '5a7b73jh6bed15c94d1e46d4',
      'master_user_info': '5a7b73f76bed15c94d1e46d4',
      'index': 0,
      'guid': 'c01da2d1-07f8-4acc-a1e3-72ddakj2Jaf8',
      'first_create': false,
      'databox_name': 'BAC',
      'datasource': 'Facebook',
      'datasource_suggestion': [{
            'source': 'Facebook',
            'page_name': 'Facebook Page 1',
            'page_id': '5a7be3f76dd15c5235d1r36d4',
            'page_country': ['Costa Rica']
      }],
      'databox_type': 'Standard',
      'location': ['Costa Rica'],
      'last_updated': 'Thurs, July 12, 2018',
      'date_created': 'Thurs, July 12, 2017',
      'expiry_date': 'Thurs, July 12, 2018',
      'mentions': 3600,
      'mentions_per_day': 8.4,
      'page_search_name': 'Facebook Page',
      'status': 'Active',
      'historical': 'Full Archive',
      'associated_account': 'William Joyce',
      'associated_email': 'william_joyce@minerva.com',
      'keywords': '4/5',
      'category_available': 20,
      'category_used': 4,
      'sub_category_available': 20,
      'sub_category_available_used': 3,
      'algorithmConnectors': ['sentiment', 'topicRecognition', 'genderAuthor', 'entityRecognition'],
      'dataConnectors': ['email', 'slack', 'appleTv'],
      'query': '( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )',
      'optional-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'required-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'excluded-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`
    },
    {
      '_id': '5a7b73f7f79f4250b93a355a',
      'master_user_info': '5a7b73f76bed15c94d1e46d4',
      'index': 1,
      'guid': 'c01da2d1-07f8-4acc-a1e3-72dda7310af8',
      'first_create': false,
      'databox_name': 'Banco Popular',
      'datasource': 'Facebook',
      'datasource_suggestion': [{
            'source': 'Facebook',
            'page_name': 'Facebook Page 2',
            'page_id': '5a7be3f76bed15c55d1r36d4',
            'page_country': ['Costa Rica']
      }],
      'databox_type': 'Plus',
      'location': ['Costa Rica'],
      'last_updated': 'Thurs, July 12, 2018',
      'date_created': 'Thurs, July 12, 2017',
      'expiry_date': 'Thurs, July 12, 2018',
      'mentions': 1200,
      'mentions_per_day': 8.4,
      'page_search_name': 'Facebook Page',
      'status': 'Active',
      'historical': 'Full Archive',
      'associated_account': 'William Joyce',
      'associated_email': 'william_joyce@minerva.com',
      'keywords': '5/5',
      'category_available': 20,
      'category_used': 3,
      'sub_category_available': 20,
      'sub_category_available_used': 0,
      'algorithmConnectors': ['sentiment', 'topicRecognition', 'genderAuthor'],
      'dataConnectors': ['email', 'slack'],
      'query': '( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )',
      'optional-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'required-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'excluded-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`
    },
    {
      '_id': '5a7be3f76bed15c55d1e46d4',
      'master_user_info': '5a7b73f7f79f4250b96a355a',
      'index': 2,
      'guid': 'c01da2d1-55e3-4acc-a1e3-72dda7310af8',
      'first_create': false,
      'databox_name': 'Banco Popular 2',
      'datasource': 'Twitter',
      'datasource_suggestion': [{
            'source': 'Twitter',
            'page_name': 'Twitter Profile',
            'page_id': '5a7be3f76bed15c55d1e46d4',
            'page_country': ['Costa Rica']
      }],
      'page_search_name': 'Twitter Profile',
      'databox_type': 'Plus',
      'location': ['Costa Rica'],
      'last_updated': 'Thurs, July 12, 2018',
      'date_created': 'Thurs, July 12, 2017',
      'expiry_date': 'Thurs, July 12, 2018',
      'mentions': 4600,
      'mentions_per_day': 8.4,
      'status': 'Paused',
      'historical': 'Full Archive',
      'associated_account': 'William Joyce',
      'associated_email': 'william_joyce@minerva.com',
      'keywords': '5/5',
      'category_available': 20,
      'category_used': 2,
      'sub_category_available': 20,
      'sub_category_available_used': 0,
      'algorithmConnectors': ['sentiment', 'topicRecognition', 'entityRecognition'],
      'dataConnectors': ['email', 'slack', 'appleTv'],
      'query': '( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )',
      'optional-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'required-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'excluded-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`
    },
    {
      '_id': '5a7b73f76bed15c938be46d4',
      'master_user_info': '5a7b73f76bed15c94d1e46d4',
      'index': 3,
      'guid': 'c01da2d1-07f8-65e2-a1e3-72dda7asB0af8',
      'first_create': false,
      'databox_name': 'Banco Nacional',
      'datasource': 'Web',
      'datasource_suggestion': [{
            'source': 'Web',
            'page_name': 'Web Name',
            'page_id': '5a7d32376bed15c55d1e46d4',
            'page_country': ['Costa Rica']
      }],
      'databox_type': 'Standard',
      'location': ['Costa Rica'],
      'last_updated': 'Thurs, July 12, 2018',
      'date_created': 'Thurs, July 12, 2017',
      'expiry_date': 'Thurs, July 12, 2018',
      'mentions': 4200,
      'mentions_per_day': 8.4,
      'page_search_name': 'Website',
      'status': 'Draft',
      'historical': 'Full Archive',
      'associated_account': 'Elena Bennet',
      'associated_email': 'elenabennett@minerva.com',
      'keywords': '3/5',
      'category_available': 20,
      'category_used': 0,
      'sub_category_available': 20,
      'sub_category_available_used': 0,
      'algorithmConnectors': ['sentiment', 'topicRecognition', 'entityRecognition'],
      'dataConnectors': ['email', 'slack'],
      'query': '( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )',
      'optional-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'required-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'excluded-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`
    },
    {
      '_id': '5a7b73f76bed15c9e8ae46d4',
      'master_user_info': '5a7b73f7f79f4250b96a355a',
      'index': 4,
      'guid': 'c01da2d1-07f8-65e2-a1e3-72dda7310af8',
      'first_create': false,
      'databox_name': 'Banco Nacional 2',
      'datasource': 'Web',
      'datasource_suggestion': [{
            'source': 'Web',
            'page_name': 'Web Name',
            'page_id': '5a7d32376bed15c55d1e46d4',
            'page_country': ['Costa Rica']
      }],
      'databox_type': 'Standard',
      'location': ['Costa Rica'],
      'last_updated': 'Thurs, July 12, 2018',
      'date_created': 'Thurs, July 12, 2017',
      'mentions': 4200,
      'mentions_per_day': 8.4,
      'page_search_name': 'Website',
      'status': 'Draft',
      'historical': 'Full Archive',
      'associated_account': 'Elena Bennet',
      'associated_email': 'elenabennett@minerva.com',
      'keywords': '3/5',
      'category_available': 20,
      'category_used': 0,
      'sub_category_available': 20,
      'sub_category_available_used': 3,
      'algorithmConnectors': ['sentiment', 'topicRecognition', 'entityRecognition'],
      'dataConnectors': ['email', 'slack'],
      'query': '( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )',
      'optional-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'required-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`,
      'excluded-keywords': `( "Hino" OR Toyota OR Lexus OR Mercedes Benz OR "KIA" OR "Fiat" OR Suzuki OR [Mase(r|rr)ati] OR "BMW" OR hyundai OR mitsubishi ) AND NOT ( contiguo OR conjunto a OR "frente a" OR "norte" OR "oeste" OR "sur" OR metros )`
    }
  ];
}
