export class DataboxTypeDB {
  public databox_type = [
    {
      '_id': '5a7b735ge4zd15c94d1e46d4',
      'index': 0,
      'guid': 'c01da2d1-07f8-4acc-a1e3-72ddakj2Jaf8',
      'data_source': 1,
      'country': 1,
      'databox_type': 'Standard',
      'keywords': 1,
      'categories': 1,
      'sub_categories': 1,
      'alerts': 'Yes',
      'email_reports': 'No',
      'enrichment': 'No',
      'price': 40,
    },
    {
      '_id': '5a7b73jh6bed15c25hal46d4',
      'index': 1,
      'guid': 'c8kda2d1-07f8-4acc-a1e3-72ddakdeJaf8',
      'data_source': 1,
      'country': 1,
      'databox_type': 'Plus',
      'keywords': 5,
      'categories': 5,
      'sub_categories': 5,
      'alerts': 'Yes',
      'email_reports': 'No',
      'enrichment': 'No',
      'price': 70,
    },
    {
      '_id': '5a7b73jh7hj315c25hal46d4',
      'index': 2,
      'guid': 'e8kda2d1-07f8-g5ht-a1e3-72ddakdeJaf8',
      'data_source': 5,
      'country': 5,
      'databox_type': 'Custom',
      'keywords': 20,
      'categories': 20,
      'sub_categories': 20,
      'alerts': 'Yes',
      'email_reports': 'Yes',
      'enrichment': 'Yes',
      'price': '',
    },
  ]
}