// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4323accb-1fd1-45b9-b60c-6afac8fcb51a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WEKYXlP5R",
    "aws_user_pools_web_client_id": "31vtnpvdn2mngjb9vneac4qkg0"
};


export default awsconfig;
